coverage:
  precision: 2
  round: nearest
  range: 60...90
  status:
    project:
      default: true
      llnl:
        threshold: 0.5
        paths:
          - lib/spack/llnl
      commands:
        threshold: 0.5
        paths:
          - lib/spack/spack/cmd
      build_systems:
        threshold: 0.5
        paths:
          - lib/spack/spack/build_systems
      modules:
        threshold: 0.5
        paths:
          - lib/spack/spack/modules
      core:
        threshold: 0.5
        paths:
          - "!lib/spack/llnl"
          - "!lib/spack/spack/cmd"

ignore:
  - lib/spack/spack/test/.*
  - lib/spack/env/.*
  - lib/spack/docs/.*
  - lib/spack/external/.*

comment: off
