config:
  install_tree: $APPS_DIR_PATH/tools/install
  source_cache: $APPS_DIR_PATH/tools/.cache
  module_roots:
    tcl: $APPS_DIR_PATH/tools/modules/tcl
    lmod: $APPS_DIR_PATH/tools/modules/lmod
  build_stage:
    - $tempdir
    - $APPS_DIR_PATH/tools/.stage
  install_path_scheme: '${ARCHITECTURE}/${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH:6}'
